# -*- coding: utf-8 -*-
"""Botswana_Maize_Production_Analysis_2016_2022

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KzCH8_EuDh-lajAegWrs5couKU_2GWdz

**Introduction**

Maize is one of the most important cereal crops in Botswana, playing a critical role in national food security and rural livelihoods. However, maize production remains highly variable, affected by fluctuating weather patterns, limited irrigation, and inconsistent agricultural support.

This project focuses on analyzing maize production trends in Botswana from 2016 to 2022, using official data sourced from the FAO (Food and Agriculture Organization). The goal is to uncover actionable insights by evaluating key indicators such as production volume, yield (tons/hectare), and area harvested.

By combining spreadsheet analysis and Python-powered data exploration, this project aims to provide a clear, data-driven foundation for future agricultural strategies. The findings will help identify performance gaps, inform resource allocation, and strengthen data storytelling for decision-makers in Botswana's agricultural sector.

**Project Objectives**

*   Analyze year-over-year trends in maize production, yield, and area harvested
*   Identify the best and worst performing years and uncover the reasons behind them

*   Provide recommendations for improving productivity and sustainability
"""

# data handling and analysis
import pandas as pd

# data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# setting visual style
sns.set(style="whitegrid")

df = pd.read_csv('/content/maize_summary_botswana.csv ')
print(df.head())

# Basic info
df.info()

# Check for nulls
print(df.isnull().sum())

# Show first few rows
df.head()

import pandas as pd

# 1. Load  cleaned summary CSV
df = pd.read_csv('/content/maize_summary_botswana.csv ')

# 2. Remove 'Grand Total' row and fixed data type
df['Year'] = df['Year'].astype(str)
df = df[df['Year'] != 'Grand Total']

# 3. Plot cleaned data
import matplotlib.pyplot as plt
import seaborn as sns


plt.figure(figsize=(12, 6))
sns.lineplot(data=df, x='Year', y='Production', label='Production (tons)', marker='o')
sns.lineplot(data=df, x='Year', y='Yield', label='Yield (tons/ha)', marker='o')
sns.lineplot(data=df, x='Year', y='Area harvested', label='Area harvested (ha)', marker='o')

plt.title('Maize Production, Yield, and Area Harvested in Botswana (2016–2023)', fontsize=14)
plt.xlabel('Year')
plt.ylabel('Value')
plt.legend()
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

import pandas as pd

# Loading the csv with no header
df = pd.read_csv('/content/maize_summary_botswana.csv ', header=None)


df.columns = ['Year', 'Production', 'Area_harvested', 'Yield', 'Other']

df = df[df['Year'] != 'Grand Total']

import pandas as pd
import matplotlib.pyplot as plt

# Load the data
df = pd.read_csv('/content/maize_summary_botswana.csv ')

df = df[df['Year'] != 'Grand Total']


df = df.sort_values('Year')

# Converting numeric columns
df[['Production', 'Area harvested', 'Yield']] = df[['Production', 'Area harvested', 'Yield']].apply(pd.to_numeric)

# --- Bar Chart: Production vs Area Harvested ---
fig, ax = plt.subplots(figsize=(10, 6))

bar_width = 0.35
years = df['Year'].astype(str)
index = range(len(years))

# Ploting bars side by side
ax.bar(index, df['Production'], bar_width, label='Production', color='cornflowerblue')
ax.bar([i + bar_width for i in index], df['Area harvested'], bar_width, label='Area Harvested', color='seagreen')

ax.set_xlabel('Year')
ax.set_ylabel('Tonnes / Hectares')
ax.set_title('Comparison of Maize Production and Area Harvested in Botswana (2016–2023)')
ax.set_xticks([i + bar_width / 2 for i in index])
ax.set_xticklabels(years, rotation=45)
ax.legend()

plt.tight_layout()
plt.show()

# --- Line Chart: Yield Trend Over Time ---
plt.figure(figsize=(10, 6))
plt.plot(df['Year'], df['Yield'], marker='o', linestyle='-', color='darkorange')
plt.xlabel('Year')
plt.ylabel('Yield (Kg/Ha)')
plt.title('Yield Trend for Maize in Botswana (2016–2023)')
plt.grid(True)
plt.tight_layout()
plt.show()

